### ISSUE TITLE
Won't start and hit with these errors, help...

### ISSUE THREAD

**Issue by sans400** [BeastlyGabi/Funkin-Forever-Engine#2]
![image](https://user-images.githubusercontent.com/78706113/214716162-c26eb4e3-39ae-48ff-8225-43905f933e5c.png)
I just got the source code, and got hit with these, what did I do? I ran the setup.bat file, help.
Nothing was edited, this is a fresh build.

**Comment by BeastlyGabi** [comment]
```
haxelib remove flixel
haxelib remove flixel-addons
haxelib install flixel
haxelib install flixel-addons
```
