### ISSUE TITLE
timer

### ISSUE THREAD

**Issue by liri1222335456** [BeastlyGabi/Funkin-Forever-Engine#3]
like psych engine or F.E underscore

**Comment by Ploxycamente2** [comment]
copy from fe underscore /j

**Comment by liri1222335456** [comment]
okay, looks like a good idea lololololololooollloloololollololololoollooloollolloolollloolloolloloolollolololol
![20221222_003614](https://user-images.githubusercontent.com/95513575/216779448-d6a0c980-3b53-47ee-abe0-2013c2132708.jpg)

**Comment by Ploxycamente2** [comment]
https://user-images.githubusercontent.com/121323138/216792342-c6a6a692-e984-4a67-8cdc-330baf64164b.mp4
